package org.example;

public class CrearE extends javax.swing.JFrame{
    /**
     * Creates new form actualizarC
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Cedula = new javax.swing.JTextField();
        Contraseña = new javax.swing.JTextField();
        ConfimarcionContraseña = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        ContraseñaAdmin = new javax.swing.JTextField();
        Registrar = new javax.swing.JLabel();
        Regresar1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        Cedula.setBackground(new java.awt.Color(255, 255, 255));
        Cedula.setForeground(new java.awt.Color(0, 0, 0));
        Cedula.setBorder(null);
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Cedula);
        Cedula.setBounds(160, 410, 250, 20);

        Contraseña.setBackground(new java.awt.Color(255, 255, 255));
        Contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Contraseña.setBorder(null);
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Contraseña);
        Contraseña.setBounds(750, 420, 250, 20);

        ConfimarcionContraseña.setBackground(new java.awt.Color(255, 255, 255));
        ConfimarcionContraseña.setForeground(new java.awt.Color(0, 0, 0));
        ConfimarcionContraseña.setBorder(null);
        ConfimarcionContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfimarcionContraseñaActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ConfimarcionContraseña);
        ConfimarcionContraseña.setBounds(760, 500, 250, 20);

        Telefono.setBackground(new java.awt.Color(255, 255, 255));
        Telefono.setForeground(new java.awt.Color(0, 0, 0));
        Telefono.setBorder(null);
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Telefono);
        Telefono.setBounds(750, 310, 250, 20);

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setBorder(null);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Nombre);
        Nombre.setBounds(160, 310, 250, 20);

        Direccion.setBackground(new java.awt.Color(255, 255, 255));
        Direccion.setForeground(new java.awt.Color(0, 0, 0));
        Direccion.setBorder(null);
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Direccion);
        Direccion.setBounds(160, 500, 250, 16);

        Correo.setBackground(new java.awt.Color(255, 255, 255));
        Correo.setForeground(new java.awt.Color(0, 0, 0));
        Correo.setBorder(null);
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Correo);
        Correo.setBounds(750, 230, 250, 20);

        ContraseñaAdmin.setBackground(new java.awt.Color(255, 255, 255));
        ContraseñaAdmin.setForeground(new java.awt.Color(0, 0, 0));
        ContraseñaAdmin.setBorder(null);
        ContraseñaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaAdminActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ContraseñaAdmin);
        ContraseñaAdmin.setBounds(160, 230, 250, 20);

        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Registrar);
        Registrar.setBounds(980, 560, 150, 40);

        Regresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regresar1MouseClicked(evt);
            }
        });
        jLayeredPane1.add(Regresar1);
        Regresar1.setBounds(130, 560, 140, 40);

        fondo.setIcon(new javax.swing.ImageIcon("Imagenes\\CrearEmpleado.jpg")); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLayeredPane1.add(fondo);
        fondo.setBounds(0, 0, 1260, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Regresar1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void ContraseñaAdminActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ConfimarcionContraseñaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actualizarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actualizarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actualizarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actualizarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearE().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField ConfimarcionContraseña;
    private javax.swing.JTextField Contraseña;
    private javax.swing.JTextField ContraseñaAdmin;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Registrar;
    private javax.swing.JLabel Regresar1;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel fondo;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration
    public CrearE() {
        initComponents();

        jLayeredPane1.setBounds(0, 0,getWidth(), getHeight());

    }

}
