package org.example;

public class Inventario extends javax.swing.JFrame{
    /**
     * Creates new form actualizarC
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        nombreProducto = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        Subtotal = new javax.swing.JTextField();
        Cantidad = new javax.swing.JSpinner();
        Agregar = new javax.swing.JLabel();
        idProducto = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        NombreCliente = new javax.swing.JTextField();
        IdCliente = new javax.swing.JTextField();
        Inventario = new javax.swing.JLabel();
        Actualizar = new javax.swing.JLabel();
        Historial = new javax.swing.JLabel();
        Facturas = new javax.swing.JLabel();
        Proveedores = new javax.swing.JLabel();
        Producto = new javax.swing.JLabel();
        Empleados = new javax.swing.JLabel();
        Clientes1 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        Descuento = new javax.swing.JLabel();
        Pagar = new javax.swing.JLabel();
        Buscar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Credito", "Debito", "Transferencia" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jComboBox1);
        jComboBox1.setBounds(710, 150, 160, 30);

        nombreProducto.setEditable(false);
        nombreProducto.setBackground(new java.awt.Color(255, 255, 255));
        nombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        nombreProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(nombreProducto);
        nombreProducto.setBounds(1080, 370, 150, 30);

        Total.setEditable(false);
        Total.setBackground(new java.awt.Color(255, 255, 255));
        Total.setForeground(new java.awt.Color(0, 0, 0));
        Total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Total);
        Total.setBounds(1080, 300, 150, 30);

        Subtotal.setBackground(new java.awt.Color(255, 255, 255));
        Subtotal.setForeground(new java.awt.Color(0, 0, 0));
        Subtotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtotalActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Subtotal);
        Subtotal.setBounds(560, 230, 150, 30);
        jLayeredPane1.add(Cantidad);
        Cantidad.setBounds(850, 230, 64, 22);

        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Agregar);
        Agregar.setBounds(1000, 220, 90, 40);

        idProducto.setBackground(new java.awt.Color(255, 255, 255));
        idProducto.setForeground(new java.awt.Color(0, 0, 0));
        idProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        idProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProductoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(idProducto);
        idProducto.setBounds(290, 230, 150, 30);

        Direccion.setBackground(new java.awt.Color(255, 255, 255));
        Direccion.setForeground(new java.awt.Color(0, 0, 0));
        Direccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Direccion);
        Direccion.setBounds(560, 150, 120, 30);

        NombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        NombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        NombreCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        NombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreClienteActionPerformed(evt);
            }
        });
        jLayeredPane1.add(NombreCliente);
        NombreCliente.setBounds(420, 150, 120, 30);

        IdCliente.setBackground(new java.awt.Color(255, 255, 255));
        IdCliente.setForeground(new java.awt.Color(0, 0, 0));
        IdCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        IdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdClienteActionPerformed(evt);
            }
        });
        jLayeredPane1.add(IdCliente);
        IdCliente.setBounds(290, 150, 120, 30);

        Inventario.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Inventario.setForeground(new java.awt.Color(255, 255, 51));
        Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventarioMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Inventario);
        Inventario.setBounds(40, 126, 90, 20);

        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Actualizar);
        Actualizar.setBounds(860, 150, 110, 30);

        Historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistorialMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Historial);
        Historial.setBounds(30, 160, 90, 30);

        Facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturasMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Facturas);
        Facturas.setBounds(30, 200, 90, 30);

        Proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProveedoresMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Proveedores);
        Proveedores.setBounds(30, 240, 120, 30);

        Producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductoMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Producto);
        Producto.setBounds(30, 280, 120, 30);

        Empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpleadosMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Empleados);
        Empleados.setBounds(30, 320, 120, 30);

        Clientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clientes1MouseClicked(evt);
            }
        });
        jLayeredPane1.add(Clientes1);
        Clientes1.setBounds(20, 360, 120, 30);

        fecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(163, 58, 175));
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("Fecha-hora");
        jLayeredPane1.add(fecha);
        fecha.setBounds(1080, 20, 140, 19);

        nombreUsuario.setBackground(new java.awt.Color(251, 228, 234));
        nombreUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(163, 58, 175));
        nombreUsuario.setText("Nombre usuario");
        jLayeredPane1.add(nombreUsuario);
        nombreUsuario.setBounds(1150, 0, 100, 19);

        Descuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescuentoMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Descuento);
        Descuento.setBounds(970, 140, 120, 40);

        Pagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PagarMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Pagar);
        Pagar.setBounds(1110, 140, 110, 40);

        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Buscar);
        Buscar.setBounds(980, 150, 110, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Cantidad", "Producto", "Valor Unidad", "Valor Total"
                }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLayeredPane1.add(jScrollPane2);
        jScrollPane2.setBounds(270, 280, 690, 250);

        fondo.setIcon(new javax.swing.ImageIcon("Imagenes\\gestion inventario.jpg")); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLayeredPane1.add(fondo);
        fondo.setBounds(0, 0, 1260, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void NombreClienteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void InventarioMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void HistorialMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void FacturasMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void ProveedoresMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void ProductoMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void EmpleadosMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Clientes1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void IdClienteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void DescuentoMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void PagarMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void idProductoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void SubtotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actualizarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actualizarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actualizarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actualizarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel Actualizar;
    private javax.swing.JLabel Agregar;
    private javax.swing.JLabel Buscar;
    private javax.swing.JSpinner Cantidad;
    private javax.swing.JLabel Clientes1;
    private javax.swing.JLabel Descuento;
    private javax.swing.JTextField Direccion;
    private javax.swing.JLabel Empleados;
    private javax.swing.JLabel Facturas;
    private javax.swing.JLabel Historial;
    private javax.swing.JTextField IdCliente;
    private javax.swing.JLabel Inventario;
    private javax.swing.JTextField NombreCliente;
    private javax.swing.JLabel Pagar;
    private javax.swing.JLabel Producto;
    private javax.swing.JLabel Proveedores;
    private javax.swing.JTextField Subtotal;
    private javax.swing.JTextField Total;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField idProducto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JLabel nombreUsuario;
    // End of variables declaration
    public Inventario() {
        initComponents();

        jLayeredPane1.setBounds(0, 0,getWidth(), getHeight());

    }
}
